/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter; 
/**
 *
 * @author abdulsametevlice
 */
public class Books_available extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Books_available.class.getName());

    private int currentPosition = -1; // O an seçili olan satır
    
    // DB config 
    private static final String DB_URL = "jdbc:mysql://localhost:3306/LIBRARY";
    private static final String DB_USER = "root";
    private static final String DB_PASSWORD = System.getenv().getOrDefault("LIBRARY_DB_PASSWORD", "Samet9160.");

    /**
     * Creates new form Books_available
     */
    public Books_available(boolean gelenYetki) {
    this.isAdmin = gelenYetki;
    initComponents();
    setLocationRelativeTo(null);
    
    // EĞER GELEN KİŞİ ADMİN DEĞİLSE HEM BUTONLARI GİZLE HEM KUTULARI KİLİTLE
    if (!isAdmin) {
        // Butonları gizliyoruz
        jButton1.setVisible(false);      // Update butonu
        btnDeleteAll.setVisible(false);  // Delete All butonu
        
        // Kutuları yazı yazılamaz (Read-Only) yapıyoruz
        txtbookid.setEditable(false);
        txtbookname.setEditable(false);
        txtauthor.setEditable(false);
        txtcopies.setEditable(false);
        txtpages.setEditable(false);
        txtyear.setEditable(false);
        
        // ComboBox'ı da (Kategori seçimi) tıklanamaz yapalım
        comboCategory.setEnabled(false);
    }
    }
    private boolean isAdmin = false;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_fetch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_back = new javax.swing.JButton();
        txtbookid = new javax.swing.JTextField();
        comboCategory = new javax.swing.JComboBox<>();
        txtbookname = new javax.swing.JTextField();
        txtauthor = new javax.swing.JTextField();
        txtcopies = new javax.swing.JTextField();
        txtpages = new javax.swing.JTextField();
        txtyear = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        btnDeleteAll = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_fetch.setBackground(new java.awt.Color(0, 102, 102));
        btn_fetch.setForeground(new java.awt.Color(255, 255, 255));
        btn_fetch.setText("Fetch");
        btn_fetch.addActionListener(this::btn_fetchActionPerformed);

        jTable1.setBackground(new java.awt.Color(248, 247, 247));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "BOOK ID", "CATEGORY", "NAME", "AUTHOR", "COPIES", "PAGES", "YEAR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btn_back.setText("Back");
        btn_back.addActionListener(this::btn_backActionPerformed);

        txtbookid.addActionListener(this::txtbookidActionPerformed);

        comboCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Science", "Fiction", "History", "Biography", "IT (Technology)", "Mystery", "Classic", "Physics", "Philosophy", "Art" }));
        comboCategory.addActionListener(this::comboCategoryActionPerformed);

        txtbookname.addActionListener(this::txtbooknameActionPerformed);

        txtauthor.addActionListener(this::txtauthorActionPerformed);

        txtcopies.addActionListener(this::txtcopiesActionPerformed);
        txtcopies.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcopiesKeyTyped(evt);
            }
        });

        txtpages.addActionListener(this::txtpagesActionPerformed);
        txtpages.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpagesKeyTyped(evt);
            }
        });

        txtyear.addActionListener(this::txtyearActionPerformed);
        txtyear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtyearKeyTyped(evt);
            }
        });

        jLabel2.setText("Book ID");

        jLabel3.setText("Category");

        jLabel4.setText("Name");

        jLabel5.setText("Author");

        jLabel6.setText("Copies");

        jLabel7.setText("Pages");

        jLabel8.setText("Year");

        jButton1.setText("Update");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        btnNext.setText("Next");
        btnNext.addActionListener(this::btnNextActionPerformed);

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(this::btnPreviousActionPerformed);

        btnExport.setText("Export to File");
        btnExport.addActionListener(this::btnExportActionPerformed);

        btnDeleteAll.setText("Delete All");
        btnDeleteAll.addActionListener(this::btnDeleteAllActionPerformed);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Books Available");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(483, 483, 483)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbookname, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtauthor, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcopies, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpages, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbookid, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExport)
                        .addGap(111, 111, 111))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 812, Short.MAX_VALUE)
                                        .addComponent(btnDeleteAll, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1))
                                .addGap(89, 89, 89))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(169, 169, 169)
                                .addComponent(btn_fetch, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbookid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbookname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtauthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcopies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpages, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(35, 35, 35)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_fetch, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteAll, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // Madde 6: Verilerin dosyaya yazılması (Zapis danych do pliku)
        try (java.io.FileWriter fw = new java.io.FileWriter("Search_Results_Backup.txt")) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            fw.write("--- SAMET'S LIBRARY SEARCH RESULTS ---\n");
            fw.write("ID | Category | Name | Author | Pages\n");
            fw.write("--------------------------------------\n");

            for (int i = 0; i < model.getRowCount(); i++) {
                String line = model.getValueAt(i, 0) + " | " +
                model.getValueAt(i, 1) + " | " +
                model.getValueAt(i, 2) + " | " +
                model.getValueAt(i, 3) + " | " +
                model.getValueAt(i, 5) + "\n";
                fw.write(line);
            }

            JOptionPane.showMessageDialog(this, "Data successfully saved to Search_Results_Backup.txt!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "File Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        int rowCount = jTable1.getRowCount();
        if (rowCount > 0 && currentPosition > 0) {
            currentPosition--;
            jTable1.setRowSelectionInterval(currentPosition, currentPosition);
            populateFields(currentPosition);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        int rowCount = jTable1.getRowCount();
        if (rowCount > 0 && currentPosition < rowCount - 1) {
            currentPosition++;
            jTable1.setRowSelectionInterval(currentPosition, currentPosition);
            populateFields(currentPosition);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id = txtbookid.getText();
        String sql = "UPDATE BOOKS SET CATEGORY=?, NAME=?, AUTHOR=?, COPIES=?, PAGES=?, PUBLISH_YEAR=? WHERE BOOK_ID=?";

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to update this book?", "Update Confirm", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
                PreparedStatement pst = conn.prepareStatement(sql)) {

                pst.setString(1, comboCategory.getSelectedItem().toString());
                pst.setString(2, txtbookname.getText());
                pst.setString(3, txtauthor.getText());
                pst.setInt(4, Integer.parseInt(txtcopies.getText()));
                pst.setInt(5, Integer.parseInt(txtpages.getText()));
                pst.setInt(6, Integer.parseInt(txtyear.getText()));
                pst.setString(7, id);

                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Updated successfully!");
                fetchBooks(); // Tabloyu yenile
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Update Error: " + e.getMessage());
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtyearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtyearKeyTyped
        onlyNumbers(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtyearKeyTyped

    private void txtyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtyearActionPerformed

    private void txtpagesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpagesKeyTyped
        onlyNumbers(evt);   // TODO add your handling code here:
    }//GEN-LAST:event_txtpagesKeyTyped

    private void txtpagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpagesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpagesActionPerformed

    private void txtcopiesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcopiesKeyTyped
        onlyNumbers(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtcopiesKeyTyped

    private void txtcopiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcopiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcopiesActionPerformed

    private void txtauthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtauthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtauthorActionPerformed

    private void txtbooknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbooknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbooknameActionPerformed

    private void comboCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCategoryActionPerformed

    private void txtbookidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbookidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbookidActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        if (isAdmin) {
        // Eğer giriş yapan Admin ise eski ana Dashboard'a git
        Dashboard dash = new Dashboard();
        dash.setVisible(true);
    } else {
        // Eğer giriş yapan User ise senin yeni yaptığın User_Dashboard'a git
        User_Dashboard userDash = new User_Dashboard();
        userDash.setVisible(true);
    }
    this.dispose(); // Şu anki sayfayı kapat
        
    }//GEN-LAST:event_btn_backActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            currentPosition = selectedRow; // Gezinti indeksini güncelle
            populateFields(selectedRow);
    }//GEN-LAST:event_jTable1MouseClicked
    }
    private void btn_fetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fetchActionPerformed
        fetchBooks();
    }//GEN-LAST:event_btn_fetchActionPerformed

    
    private void btnDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAllActionPerformed
int firstConfirm = JOptionPane.showConfirmDialog(this, 
        "You are about to DELETE ALL books. Are you sure?", "CRITICAL WARNING", 
        JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
    
    if (firstConfirm == JOptionPane.YES_OPTION) {
        int secondConfirm = JOptionPane.showConfirmDialog(this, 
            "REALLY? This will clear the entire database! Final decision?", "FINAL CONFIRMATION", 
            JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        
        if (secondConfirm == JOptionPane.YES_OPTION) {
            try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)) {
                
                // Madde 4: Archive data before deletion (Trash Bin logic)
                backupBeforeDeleteAll(); 

                String sql = "DELETE FROM BOOKS";
                try (PreparedStatement pst = conn.prepareStatement(sql)) {
                    int deletedRows = pst.executeUpdate();
                    
                    // Clear the table view
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                    model.setRowCount(0);
                    
                    JOptionPane.showMessageDialog(this, deletedRows + " books deleted successfully. Backup saved to Trash_Bin.txt.");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Deletion Error: " + e.getMessage());
            }
        }
    }

    }//GEN-LAST:event_btnDeleteAllActionPerformed

    private void backupBeforeDeleteAll() {
    try (java.io.FileWriter fw = new java.io.FileWriter("Trash_Bin.txt", true)) {
        fw.write("\n--- BULK DELETE OPERATION (" + new java.util.Date() + ") ---\n");
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            // Using indices based on our Madde 2 Checkbox structure (0: Select, 1: ID, 3: Name)
            fw.write("ID: " + jTable1.getValueAt(i, 1) + " | Title: " + jTable1.getValueAt(i, 3) + "\n");
        }
        fw.write("------------------------------------------\n");
    } catch (Exception e) {
        System.out.println("Backup error: " + e.getMessage());
    }
}
    private void onlyNumbers(java.awt.event.KeyEvent evt) {
    char c = evt.getKeyChar();
    if (!Character.isDigit(c)) {
        evt.consume(); // Eğer rakam değilse girdiyi yok sayar
    }
}        
    private void populateFields(int row) {  //Yardımcı Metot: Tablodaki veriyi kutucuklara doldurur
        txtbookid.setText(jTable1.getValueAt(row, 0).toString());
        comboCategory.setSelectedItem(jTable1.getValueAt(row, 1).toString());
        txtbookname.setText(jTable1.getValueAt(row, 2).toString());
        txtauthor.setText(jTable1.getValueAt(row, 3).toString());
        txtcopies.setText(jTable1.getValueAt(row, 4).toString());
        txtpages.setText(jTable1.getValueAt(row, 5).toString());
        txtyear.setText(jTable1.getValueAt(row, 6).toString());
}
    
    
private void fetchBooks() {
    try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
         PreparedStatement pst = conn.prepareStatement("SELECT BOOK_ID, CATEGORY, NAME, AUTHOR, COPIES, PAGES, PUBLISH_YEAR FROM BOOKS");
         ResultSet rs = pst.executeQuery()) {

        // 1. Tablo Modelini Tanımlıyoruz (Sorting ve Editable Koruması Dahil)
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"BOOK ID", "CATEGORY", "NAME", "AUTHOR", "COPIES", "PAGES", "YEAR"}, 0
        ) {
            // BURAYI EKLEDİK: Kullanıcı hücrelere çift tıklasa bile içine yazamaz
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex >= 4 && columnIndex <= 6) {
                    return Integer.class;
                }
                return String.class;
            }
        };

        jTable1.setModel(model);
        jTable1.setRowSorter(new TableRowSorter<>(model));

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("BOOK_ID"),
                rs.getString("CATEGORY"),
                rs.getString("NAME"),
                rs.getString("AUTHOR"),
                rs.getInt("COPIES"),
                rs.getInt("PAGES"),
                rs.getInt("PUBLISH_YEAR")
            });
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "DB Error: " + e.getMessage());
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
            java.awt.EventQueue.invokeLater(() -> {
            // Buraya 'true' ekledik ki sayfa tek başına çalışırken hata vermesin
            new Books_available(true).setVisible(true); 
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteAll;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_fetch;
    private javax.swing.JComboBox<String> comboCategory;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtauthor;
    private javax.swing.JTextField txtbookid;
    private javax.swing.JTextField txtbookname;
    private javax.swing.JTextField txtcopies;
    private javax.swing.JTextField txtpages;
    private javax.swing.JTextField txtyear;
    // End of variables declaration//GEN-END:variables
}

