/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abdulsametevlice
 */
public class Remove_Staffs extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Remove_Staffs.class.getName());
    
    // DB config
    private static final String DB_URL = System.getenv().getOrDefault("LIBRARY_DB_URL", "jdbc:mysql://localhost:3306/LIBRARY");
    private static final String DB_USER = "root";
    private static final String DB_PASSWORD = System.getenv().getOrDefault("LIBRARY_DB_PASSWORD", "Samet9160.");
    private static final String DEFAULT_STAFF_TABLE = System.getenv().getOrDefault("LIBRARY_STAFF_TABLE", "STAFF");

    /**
     * Creates new form Remove_Staffs
     */
    public Remove_Staffs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtstaffid = new javax.swing.JTextField();
        txtstaffname = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("ENTER STAFF İD OR NAME TO REMOVE ");

        jLabel1.setText("STAFF ID");

        jLabel2.setText("STAFF NAME ");

        txtstaffid.addActionListener(this::txtstaffidActionPerformed);

        txtstaffname.addActionListener(this::txtstaffnameActionPerformed);

        btnAdd.setBackground(new java.awt.Color(0, 102, 102));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("REMOVE");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnBack.setText("BACK");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(txtstaffid, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtstaffname, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtstaffid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtstaffname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Remove Staffs");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String id = txtstaffid.getText().trim();
        String name = txtstaffname.getText().trim();

        if (id.isEmpty() && name.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter Staff ID or Name.");
            return;
        }

        String staffTable = resolveStaffTableName();

        final String sql;
        final String param;
        if (!id.isEmpty()) {
            sql = "DELETE FROM " + staffTable + " WHERE STAFF_ID = ?";
            param = id;
        } else {
            sql = "DELETE FROM " + staffTable + " WHERE NAME = ?";
            param = name;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete staff by " + (!id.isEmpty() ? "ID" : "Name") + "?\nValue: " + param,
            "Confirm Delete",
            javax.swing.JOptionPane.YES_NO_OPTION
        );
        if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

        try (java.sql.Connection conn = java.sql.DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)) {
            // Önce staff'ın ismini al
            String staffName = null;
            String selectSql;
            if (!id.isEmpty()) {
                selectSql = "SELECT NAME FROM " + staffTable + " WHERE STAFF_ID = ?";
            } else {
                selectSql = "SELECT NAME FROM " + staffTable + " WHERE NAME = ?";
            }
            
            try (java.sql.PreparedStatement selectPst = conn.prepareStatement(selectSql)) {
                selectPst.setString(1, param);
                try (java.sql.ResultSet rs = selectPst.executeQuery()) {
                    if (rs.next()) {
                        staffName = rs.getString("NAME");
                    }
                }
            }
            
            if (staffName == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "No matching staff found.");
                return;
            }
            
            // Şimdi sil
            try (java.sql.PreparedStatement pst = conn.prepareStatement(sql)) {
                pst.setString(1, param);
                int rows = pst.executeUpdate();

                if (rows > 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, staffName + " staff deleted successfully.");
                    txtstaffid.setText("");
                    txtstaffname.setText("");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "No matching staff found.");
                }
            }
        } catch (java.sql.SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Error deleting staff", e);
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "DB Error: " + e.getMessage()
                    + "\n\nConfig:"
                    + "\nDB_URL=" + DB_URL
                    + "\nDB_USER=" + DB_USER
                    + "\nSTAFF_TABLE=" + staffTable
            );
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Dashboard dash = new Dashboard();
        dash.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtstaffidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstaffidActionPerformed
        if (!txtstaffid.getText().trim().isEmpty()) {
            btnAddActionPerformed(evt);
        }
    }//GEN-LAST:event_txtstaffidActionPerformed

    private void txtstaffnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstaffnameActionPerformed
        if (!txtstaffname.getText().trim().isEmpty()) {
            btnAddActionPerformed(evt);
        }
    }//GEN-LAST:event_txtstaffnameActionPerformed
    
    private String resolveStaffTableName() {
        String base = DEFAULT_STAFF_TABLE;

        if (tableExists(base)) return base;
        String lower = base.toLowerCase();
        if (tableExists(lower)) return lower;
        String upper = base.toUpperCase();
        if (tableExists(upper)) return upper;

        String discovered = discoverStaffLikeTable();
        if (discovered != null) return discovered;

        return base;
    }

    private boolean tableExists(String tableName) {
        String sql = "SELECT 1 FROM information_schema.tables WHERE table_schema = DATABASE() AND table_name = ? LIMIT 1";
        try (java.sql.Connection conn = java.sql.DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
             java.sql.PreparedStatement pst = conn.prepareStatement(sql)) {
            pst.setString(1, tableName);
            try (java.sql.ResultSet rs = pst.executeQuery()) {
                return rs.next();
            }
        } catch (java.sql.SQLException e) {
            return false;
        }
    }

    private String discoverStaffLikeTable() {
        String sql = "SELECT table_name FROM information_schema.tables "
            + "WHERE table_schema = DATABASE() AND LOWER(table_name) LIKE ? "
            + "ORDER BY table_name LIMIT 1";
        try (java.sql.Connection conn = java.sql.DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
             java.sql.PreparedStatement pst = conn.prepareStatement(sql)) {
            pst.setString(1, "%staff%");
            try (java.sql.ResultSet rs = pst.executeQuery()) {
                if (rs.next()) return rs.getString(1);
                return null;
            }
        } catch (java.sql.SQLException e) {
            return null;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> new Remove_Staffs().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtstaffid;
    private javax.swing.JTextField txtstaffname;
    // End of variables declaration//GEN-END:variables
}
